[format]
# String quote style (single/double/preserve)
quote-style = 'single'

[lint]
# List of linter rules to enable
# https://docs.astral.sh/ruff/rules/
select = ["E4", "E7", "E9", "F", "S", "D", "W505"]
# List of linter rules to ignore
ignore = ["D102", "D107"]

[lint.pydocstyle]
# Docstrings style
convention = "google"

[lint.pycodestyle]
# Dostrings max length
max-doc-length = 72